name: flutter_shadcn_cli
description: CLI for the shadcn_flutter registry.
version: 0.1.5
repository: https://github.com/ibrar-x/flutter_shadcn_cli
homepage: https://github.com/ibrar-x/flutter_shadcn_cli

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  json_annotation: ^4.8.1
  dcli: ^4.0.1 # Using dcli for easier file operations and user interaction if needed, or just dart:io
  prompts: ^2.0.0 # For user interaction
  yaml: ^3.1.2
  http: ^1.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5

executables:
  flutter_shadcn: flutter_shadcn
  shadcn: shadcn
